const books=[
 {id:'sub-terra',title:'Sub terra',author:'Baldomero Lillo',type:'Relatos',place:'Chile',color:'blue',desc:'Ocho relatos donde el carbón, la pobreza y la dignidad humana sostienen una lectura intensa y muy chilena.',year:'1904'},
 {id:'martin-rivas',title:'Martín Rivas',author:'Alberto Blest Gana',type:'Novela',place:'Chile',color:'red',desc:'Una historia de ambición, amor y diferencias de clase en el Santiago del siglo XIX.',year:'1862'},
 {id:'juana-lucero',title:'Juana Lucero',author:"Augusto D'Halmar",type:'Novela',place:'Chile',color:'yellow',desc:'Una joven enfrenta una ciudad marcada por las apariencias, la desigualdad y la búsqueda de libertad.',year:'1902'},
 {id:'cuentos-amor',title:'Cuentos de amor, de locura y de muerte',author:'Horacio Quiroga',type:'Cuentos',place:'Latinoamérica',color:'purple',desc:'Relatos breves, tensos y memorables, situados entre la naturaleza, el deseo y el peligro.',year:'1917'},
 {id:'frankenstein',title:'Frankenstein',author:'Mary Shelley',type:'Gótico',place:'Universal',color:'brown',desc:'La historia de una criatura abandonada por su creador y una pregunta que todavía incomoda.',year:'1818'},
 {id:'dracula',title:'Drácula',author:'Bram Stoker',type:'Gótico',place:'Universal',color:'pink',desc:'Cartas, diarios y telegramas forman una persecución obsesiva contra el vampiro más famoso de la literatura.',year:'1897'},
 {id:'jekyll-hyde',title:'Jekyll y Hyde',author:'R. L. Stevenson',type:'Misterio',place:'Universal',color:'navy',desc:'Un experimento libera la parte más oscura de un hombre respetable.',year:'1886'},
 {id:'isla-tesoro',title:'La isla del tesoro',author:'R. L. Stevenson',type:'Aventura',place:'Universal',color:'green',desc:'Un mapa, un tesoro y una tripulación donde nadie parece ser exactamente quien dice ser.',year:'1883'},
 {id:'dorian-gray',title:'El retrato de Dorian Gray',author:'Oscar Wilde',type:'Novela',place:'Universal',color:'blue',desc:'Un joven conserva su apariencia mientras un retrato registra el costo de sus decisiones.',year:'1890'},
 {id:'gigante-egoista',title:'El gigante egoísta',author:'Oscar Wilde',type:'Cuento',place:'Universal',color:'yellow',desc:'Un gigante descubre que su jardín solo vuelve a florecer cuando aprende a compartirlo.',year:'1888'},
 {id:'arte-guerra',title:'El arte de la guerra',author:'Sun Tzu',type:'Pensamiento',place:'Universal',color:'red',desc:'Ideas breves sobre estrategia, decisión y conflicto para leer y discutir con calma.',year:'Antigüedad'},
 {id:'meditaciones',title:'Meditaciones',author:'Marco Aurelio',type:'Pensamiento',place:'Universal',color:'purple',desc:'Notas personales sobre disciplina, tiempo, comunidad y cómo vivir con incertidumbre.',year:'Siglo II'},
 {id:'sub-sole',title:'Sub sole',author:'Baldomero Lillo',type:'Relatos',place:'Chile',color:'green',desc:'Relatos donde el mundo rural, la naturaleza y la desigualdad revelan nuevas formas de conflicto.',year:'1907'},
 {id:'azul',title:'Azul...',author:'Rubén Darío',type:'Poesía',place:'Latinoamérica',color:'blue',desc:'Poemas y cuentos que abren el modernismo hispanoamericano con una mirada musical y visual.',year:'1888'},
 {id:'tradiciones',title:'Tradiciones peruanas',author:'Ricardo Palma',type:'Relatos',place:'Latinoamérica',color:'brown',desc:'Historias breves que mezclan memoria, humor e imaginación para recorrer el pasado peruano.',year:'1872'},
 {id:'niebla',title:'Niebla',author:'Miguel de Unamuno',type:'Novela',place:'Universal',color:'navy',desc:'Una novela inquieta que juega con la identidad, la ficción y la libertad de sus personajes.',year:'1914'},
 {id:'lazarillo',title:'Lazarillo de Tormes',author:'Anónimo',type:'Novela',place:'Universal',color:'yellow',desc:'Un joven sobrevive cambiando de amo en una crítica ingeniosa a la sociedad de su tiempo.',year:'1554'},
 {id:'leyendas',title:'Leyendas',author:'Gustavo Adolfo Bécquer',type:'Cuentos',place:'Universal',color:'purple',desc:'Relatos breves de misterio, amor y apariciones para entrar al romanticismo español.',year:'1871'},
 {id:'quijote',title:'Don Quijote',author:'Miguel de Cervantes',type:'Novela',place:'Universal',color:'red',desc:'Una ruta guiada por capítulos para descubrir humor, aventura y la fuerza de imaginar otro mundo.',year:'1605'},
 {id:'poesia-mistral',title:'Poesía chilena clásica',author:'Selección editorial',type:'Poesía',place:'Chile',color:'pink',desc:'Una ruta de lectura sobre voz poética, paisaje, identidad y recursos literarios.',year:'Colección'}
];
const guides=[['sub-terra','Sub terra: minería, naturalismo y desigualdad','Contexto social, narrador, símbolos y preguntas de análisis.'],['martin-rivas','Martín Rivas: clase, ciudad y ascenso social','Personajes, conflicto central y lectura del Chile del siglo XIX.'],['juana-lucero','Juana Lucero: identidad, ciudad y desigualdad','Una ruta para leer protagonista, entorno y tensiones sociales.'],['cuentos-amor','Quiroga: tensión, atmósfera y desenlace','Cómo reconocer pistas y explicar la fuerza de un cuento breve.'],['frankenstein','Frankenstein: ciencia, ética y monstruos','Qué hace humano a un personaje y cómo argumentarlo.'],['dracula','Drácula: miedo, forma epistolar y deseo','Cómo leer una novela construida con múltiples voces.'],['jekyll-hyde','Jekyll y Hyde: doble identidad y misterio','Claves para analizar secreto, narrador y transformación.'],['isla-tesoro','La isla del tesoro: aventura y decisiones','Narrador, viaje del héroe y conflictos de lealtad.'],['sub-sole','Sub sole: naturaleza y conflicto social','Relatos chilenos para comparar mundo rural, destino y desigualdad.'],['azul','Azul...: modernismo y lenguaje poético','Imágenes, musicalidad y símbolos para leer poesía con seguridad.'],['tradiciones','Tradiciones peruanas: memoria y humor','Cómo distinguir narrador, anécdota e identidad cultural.'],['niebla','Niebla: identidad, ficción y libertad','Una guía para leer metaficción sin perder el hilo.'],['lazarillo','Lazarillo: crítica social y picaresca','Narrador protagonista, ironía y supervivencia.'],['quijote','Don Quijote: imaginación, humor y aventura','Ruta por capítulos para comprender pares de personajes y parodia.']];
const q=new URLSearchParams(location.search);let view=q.get('vista')||'inicio';let selected=q.get('libro')||'sub-terra';
const link=(vista,extra='')=>`?vista=${vista}${extra}`;
const sourceUrl=b=>({
 'sub-terra':'https://es.wikisource.org/wiki/Autor:Baldomero_Lillo',
 'sub-sole':'https://es.wikisource.org/wiki/Sub_sole_(1907)',
 'martin-rivas':'https://www.memoriachilena.gob.cl/602/w3-article-3670.html',
 'quijote':'https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads',
 'lazarillo':'https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads',
 'azul':'https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads',
 'tradiciones':'https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads',
 'niebla':'https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads',
 'frankenstein':'https://www.gutenberg.org/',
 'dracula':'https://www.gutenberg.org/'
}[b.id]||'https://www.gutenberg.org/');
const sourcePage=b=>({'sub-terra':'Sub terra (1904)','sub-sole':'Sub sole (1907)','tradiciones':'Tradiciones peruanas','meditaciones':'Meditaciones','cuentos-amor':'Cuentos de amor, de locura y de muerte','gigante-egoista':'El gigante egoista'}[b.id]||'');
const sourcePdf=b=>({'sub-terra':'https://commons.wikimedia.org/wiki/Special:FilePath/Sub_Terra.pdf','sub-sole':'https://commons.wikimedia.org/wiki/Special:FilePath/Sub_Sole.pdf'}[b.id]||'');
const audioUrl=b=>{
  const direct={'lazarillo':'https://librivox.org/lazarillo-de-tormes/','frankenstein':'https://librivox.org/frankenstein-el-moderno-prometeo-by-mary-wollstonecraft-shelley/','quijote':'https://librivox.org/don-quijote-vol-1-by-miguel-de-cervantes-saavedra/'};
  return direct[b.id]||`https://librivox.org/search?title=${encodeURIComponent(b.title)}&recorded_language=es`;
};
function nav(){return `<nav><div class="wrap nav-in"><a class="brand" href="${link('inicio')}"><span class="mark"></span>Umbral</a><div class="nav-links"><a href="${link('catalogo')}">Biblioteca</a><a href="${link('guias')}">Guías PAES</a><a href="${link('rutas')}">Rutas</a><a href="${link('recursos')}">Recursos gratis</a><a class="pill" href="${link('planes')}">Umbral Plus</a></div></div></nav>`}
function footer(){return `<footer class="footer"><div class="wrap foot"><span>Umbral · Biblioteca digital</span><span>Clásicos, guías y lectura sin distracciones</span></div></footer>`}
function bookCard(b){return `<a class="book ${b.color}" href="${link('libro','&libro='+b.id)}"><small>${b.type} · ${b.place}</small><div class="book-title">${b.title}</div><div class="book-footer"><span>${b.author}</span><i class="circle">↗</i></div></a>`}
function home(){return `<main><section class="hero"><div class="wrap"><span class="eyebrow">Biblioteca digital chilena</span><h1>Leer un clásico no debería sentirse como rendir una prueba.</h1><p class="lead">Textos esenciales, explicados con contexto. Una biblioteca para descubrir historias, estudiar mejor y volver a disfrutar la lectura.</p><div class="actions"><a class="button" href="${link('catalogo')}">Entrar a la biblioteca <span>→</span></a><a class="button alt" href="${link('guias')}">Ver guías PAES</a></div></div></section><section class="metrics"><div class="wrap"><div class="metric"><b>20</b><span>clásicos en la colección inicial</span></div><div class="metric"><b>14</b><span>guías de lectura disponibles</span></div><div class="metric"><b>0</b><span>anuncios que interrumpan tu lectura</span></div></div></section><section class="section"><div class="wrap"><div class="head"><div><span class="eyebrow">Colección 01 · Dominio público</span><h2>Libros que siguen hablando.</h2></div><a class="text-link" href="${link('catalogo')}">Ver los 20 títulos →</a></div><div class="books">${books.slice(0,4).map(bookCard).join('')}</div></div></section><section class="guide-band"><div class="wrap guide-grid"><div><span class="eyebrow" style="color:#e7a83d">Guías para estudiar</span><h2>Entiende la lectura antes de memorizarla.</h2><p>Cada guía toma una obra y la vuelve cercana: personajes, símbolos, contexto y preguntas para conversar o prepararte para la PAES.</p><a class="button" style="background:#e7a83d;color:#172021" href="${link('guias')}">Explorar las guías →</a></div><div class="steps"><div class="step"><b>01</b><div><strong>Lee a tu ritmo</strong><span>Textos ordenados, legibles y sin distracciones.</span></div></div><div class="step"><b>02</b><div><strong>Abre la guía cuando la necesites</strong><span>Contexto, ideas principales y personajes sin arruinar la experiencia.</span></div></div><div class="step"><b>03</b><div><strong>Comprueba lo que entendiste</strong><span>Preguntas breves para conectar la obra con tus propias ideas.</span></div></div></div></div></section></main>`}
function catalogue(){return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / Biblioteca</div><span class="eyebrow">Colección 01</span><h1 style="font-size:clamp(3rem,6vw,5.4rem);max-width:760px">Una biblioteca para empezar bien.</h1><p class="lead">Selección inicial de clásicos. Cada ficha tendrá lectura, contexto, guía y preguntas para practicar.</p><div class="filters"><button class="filter active" data-filter="todos">Todos</button><button class="filter" data-filter="Chile">Chile</button><button class="filter" data-filter="Latinoamérica">Latinoamérica</button><button class="filter" data-filter="Universal">Universal</button></div><div class="books" id="catalogue-books">${books.map(bookCard).join('')}</div><p class="catalogue-note">Demo: antes de publicar textos completos se revisa que la obra y la traducción usada estén en dominio público o tengan la licencia adecuada.</p></div></main>`}
function bookPage(b){let internal=sourcePage(b);return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / <a href="${link('catalogo')}">Biblioteca</a> / ${b.title}</div><section class="book-hero"><div class="cover ${b.color}"><small>${b.type} · ${b.place}</small><div class="book-title">${b.title}</div><div class="book-footer"><span>${b.author}</span><span>${b.year}</span></div></div><div><span class="eyebrow">${b.type} · ${b.place}</span><h1 style="font-size:clamp(3.2rem,6vw,5.4rem);margin-bottom:16px">${b.title}</h1><p class="meta">${b.author} · ${b.year}<br>${b.desc}</p><div><span class="tag">Lectura estimada: 3 h</span><span class="tag">Guía incluida</span><span class="tag">Nivel: medio</span><span class="tag">Audiolibro en LibriVox</span></div><div class="actions"><a class="button" href="${link('leer','&libro='+b.id)}">Leer en Umbral →</a><a class="button alt" href="${link('guia','&libro='+b.id)}">Estudiar con la guía</a><a class="button alt" href="${audioUrl(b)}" target="_blank" rel="noopener">▶ Escuchar audiolibro</a></div><p class="catalogue-note">${internal?'Esta obra se lee dentro de Umbral.':'Esta obra se abre en Umbral; las ediciones íntegras disponibles se cargan aquí y las que siguen en preparación muestran la guía y el audiolibro.'}</p></div></section><section class="reader" id="lector"><div class="reader-top"><span>ANTES DE LEER</span><span>2 minutos</span></div><article class="reader-body"><p><strong>Qué vas a encontrar:</strong> ${b.desc}</p><p>Lee primero la obra completa y vuelve aquí después si quieres ordenar tus ideas, revisar el contexto o practicar con preguntas tipo PAES.</p><a class="button" href="${link('guia','&libro='+b.id)}">Abrir guía de ${b.title} →</a></article></section></div></main>`}
function internalReader(b){let pdf=sourcePdf(b);if(pdf)return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('catalogo')}">Biblioteca</a> / <a href="${link('libro','&libro='+b.id)}">${b.title}</a> / Leer</div><section class="premium-reader premium-pdf" id="premium-reader"><div class="premium-top"><span>${b.author.toUpperCase()} · ${b.title.toUpperCase()} · EDICIÓN COMPLETA</span><div class="premium-tools"><a class="simple-btn" href="${link('guia','&libro='+b.id)}">Guía</a></div></div><iframe title="${b.title}, lectura completa" src="${pdf}" style="display:block;width:100%;height:76vh;border:0;background:#fdfaf4"></iframe><div class="premium-credit">Edición original digital de ${b.author}, ${b.year}. Fuente: Wikimedia Commons, dominio público; se conserva la atribución.</div></section></div></main>`;return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('catalogo')}">Biblioteca</a> / <a href="${link('libro','&libro='+b.id)}">${b.title}</a> / Leer</div><div class="reader-card" id="reader-card"><header class="reader-head"><div class="reader-title"><span class="eyebrow">Texto completo · dentro de Umbral</span><h1 class="reader-h1">${b.title}</h1><p class="reader-sub">${b.author} · ${b.year} · ${b.type} · ${b.place}</p></div><div class="reader-tools"><button id="fr-minus" class="rtool" aria-label="Disminuir letra">A−</button><span class="rtool-size" id="rtool-size">100%</span><button id="fr-plus" class="rtool" aria-label="Aumentar letra">A+</button><button id="fr-theme" class="rtool" aria-label="Cambiar tema" title="Tema claro / noche">◐</button></div></header><article class="reader-body" id="reader-text"><p class="reader-loading">Cargando texto completo…</p></article><div class="read-ctrl" id="read-ctrl" hidden><button class="read-btn" id="read-prev" aria-label="Página anterior">‹</button><div class="read-mid"><div class="read-progress" id="read-bar"><span id="read-fill"></span></div><span class="read-meta" id="read-meta"></span></div><button class="read-btn" id="read-next" aria-label="Página siguiente">›</button><span class="read-hint">← → para pasar página</span></div><footer class="reader-foot"><a class="simple-btn" href="${link('guia','&libro='+b.id)}">Estudiar con la guía →</a><a class="simple-btn" href="${audioUrl(b)}" target="_blank" rel="noopener">▶ Escuchar audiolibro</a></footer></div><p class="reader-credit">Texto íntegro reproducido por página, dominio público · Umbral</p></main>`;}
function guideList(){return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / Guías PAES</div><span class="eyebrow">Estudiar sin apagar la lectura</span><h1 style="font-size:clamp(3rem,6vw,5.4rem);max-width:800px">Guías que te ayudan a pensar, no a copiar.</h1><p class="lead">Contexto, personajes, ideas y práctica. Estas son las guías de la primera colección.</p><div class="guide-list">${guides.map((g,i)=>`<article class="guide-card"><b>0${i+1}</b><div><h3>${g[1]}</h3><p>${g[2]}</p></div><a class="simple-btn" href="${link('guia','&libro='+g[0])}">Abrir guía →</a></article>`).join('')}</div></div></main>`}
function guidePage(b){return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / <a href="${link('guias')}">Guías PAES</a> / ${b.title}</div><span class="eyebrow">Guía de lectura · Demo</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);max-width:760px">${b.title}, para entenderla de verdad.</h1><p class="lead">Una estructura simple para prepararte, participar en clases o rendir una evaluación con más seguridad.</p><section class="study"><article class="card"><h3>Antes de leer</h3><p>${b.desc}</p><p><strong>Fíjate en:</strong> quién cuenta la historia, qué desea el personaje principal y qué obstáculo transforma su camino.</p><h3 style="margin-top:30px">Preguntas para pensar</h3><div class="question">01 · ¿Cuál es el conflicto que pone en movimiento la obra?</div><div class="question">02 · ¿Qué crítica o tensión de su época aparece en la historia?</div><div class="question">03 · Elige un símbolo y explica qué representa.</div><div class="question">04 · ¿Qué cambia en el personaje al final?</div></article><aside class="card"><h3>En tu ficha</h3><p><strong>Autor:</strong><br>${b.author}</p><p><strong>Género:</strong><br>${b.type}</p><p><strong>Origen:</strong><br>${b.place}</p><a class="button" style="margin-top:10px" href="${link('libro','&libro='+b.id)}">Ir al lector →</a></aside></section></div></main>`}
function join(){return `<main class="page"><div class="wrap signup"><span class="eyebrow">Primer capítulo</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);margin:14px auto 18px">Una mejor forma de acercarse a los libros.</h1><p class="lead" style="margin:auto">Recibe una lectura recomendada, una idea y una guía cada semana. Sin spam. Sin presión.</p><form class="form" id="join-form"><input aria-label="Tu correo" type="email" required placeholder="tu@correo.cl"><button>Quiero leer</button></form><p id="form-message" class="catalogue-note">Esto es una demostración: después se conecta a Brevo, Mailchimp o una lista de espera real.</p></div></main>`}
function plans(){return `<main class="page"><div class="wrap"><span class="eyebrow">Acceso Umbral</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);max-width:760px">Lee libre. Profundiza cuando lo necesites.</h1><p class="lead">La biblioteca es el comienzo. Umbral Plus reúne las guías completas, práctica y nuevas colecciones cada mes.</p><section class="study"><article class="card"><h3>Umbral Libre</h3><p><strong style="font:800 2.4rem var(--serif);color:#172021">$0</strong> · siempre</p><p>Catálogo abierto, fichas de lectura y una guía de muestra semanal.</p><a class="button alt" href="${link('catalogo')}">Explorar gratis</a></article><aside class="card"><span class="eyebrow">Recomendado</span><h3>Umbral Plus</h3><p><strong style="font:800 2.4rem var(--serif);color:#172021">$3.990</strong> · al mes</p><p>Guías PAES completas, preguntas nuevas cada semana, planes de lectura, marcadores y acceso anticipado a las nuevas colecciones.</p><a class="button" href="${link('checkout')}">Continuar al pago →</a><p class="catalogue-note">Pago seguro. Cancela cuando quieras.</p></aside></section></div></main>`}
function checkout(){return `<main class="page"><div class="wrap signup"><span class="eyebrow">Umbral Plus</span><h1 style="font-size:clamp(3rem,6vw,5rem);margin:14px auto 18px">Estás a un paso de entrar.</h1><p class="lead" style="margin:auto">El pago se realiza de forma 100% segura. Al confirmar, recibirás acceso a Umbral Plus en tu correo.</p><div class="card" style="margin-top:32px;text-align:left"><h3>Tu acceso incluye</h3><p>✓ Guías PAES completas<br>✓ Planes de lectura<br>✓ Nuevas colecciones cada mes<br>✓ Material de práctica descargable</p><a class="button" href="/contacto/?producto=Umbral">Solicitar acceso / Suscribirse →</a><p class="catalogue-note">Pago procesado de forma segura. Recibirás la confirmación e instrucciones por correo.</p></div></div></main>`}
function resources(){return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / Recursos gratuitos</div><span class="eyebrow">Para seguir aprendiendo</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);max-width:780px">Recursos gratuitos que vale la pena guardar.</h1><p class="lead">Bibliotecas públicas y materiales abiertos para ampliar tus lecturas. Umbral selecciona y orienta; cada recurso enlaza a su fuente original.</p><section class="study"><article class="card"><h3>Clásicos chilenos</h3><p><strong>Sub terra, Sub sole y Martín Rivas</strong><br>La Biblioteca Nacional reúne contexto, imágenes y documentos de autores chilenos. Ideal para armar rutas de lectura sobre realismo, minería y sociedad chilena.</p><a class="button" href="https://www.memoriachilena.gob.cl/602/w3-article-3708.html" target="_blank" rel="noopener">Abrir Memoria Chilena →</a></article><aside class="card"><h3>Clásicos en español</h3><p><strong>Don Quijote, Lazarillo de Tormes, Azul..., Tradiciones peruanas y Niebla.</strong><br>Una selección abierta para descubrir obras que ya tienen lectores, reseñas y mucho potencial para nuevas guías de Umbral.</p><a class="button" href="https://www.gutenberg.org/ebooks/bookshelf/420?sort_order=downloads" target="_blank" rel="noopener">Explorar clásicos →</a></aside></section><section class="study"><article class="card"><h3>Guías gratuitas de Umbral</h3><p>Empieza por una guía breve y luego pasa a la lectura. Estas rutas son propias y pueden crecer sin depender de licencias externas.</p><p><a class="text-link" href="${link('guia','&libro=sub-terra')}">Sub terra: minería y desigualdad →</a></p><p><a class="text-link" href="${link('guia','&libro=frankenstein')}">Frankenstein: ciencia y ética →</a></p><p><a class="text-link" href="${link('guia','&libro=dracula')}">Drácula: miedo y voces →</a></p></article><aside class="card"><h3>Para estudio académico</h3><p>OpenStax ofrece libros universitarios gratuitos y revisados por pares en áreas como economía, ciencias, matemática y computación. Úsalos como enlace recomendado; revisa la licencia específica antes de reutilizar contenido dentro de Umbral.</p><a class="button" href="https://openstax.org/subjects" target="_blank" rel="noopener">Ver materias abiertas →</a></aside></section></div></main>`}
function routes(){return `<main class="page"><div class="wrap"><div class="crumb"><a href="${link('inicio')}">Umbral</a> / Rutas de lectura</div><span class="eyebrow">Elige por interés</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);max-width:780px">No necesitas saber qué leer. Solo cómo quieres sentirte.</h1><p class="lead">Rutas breves para descubrir un tema, preparar una prueba o recuperar el hábito de leer.</p><section class="study"><article class="card"><h3>Chile en 4 lecturas</h3><p>Del carbón de Lota a la ciudad del siglo XIX: <em>Sub terra</em>, <em>Sub sole</em>, <em>Martín Rivas</em> y <em>Juana Lucero</em>.</p><a class="button" href="${link('libro','&libro=sub-terra')}">Comenzar ruta →</a></article><aside class="card"><h3>Historias que atrapan</h3><p>Para volver a leer sin presión: <em>Jekyll y Hyde</em>, <em>El gigante egoísta</em>, <em>La isla del tesoro</em> y cuentos de Quiroga.</p><a class="button" href="${link('libro','&libro=jekyll-hyde')}">Ver primeras lecturas →</a></aside></section><section class="study"><article class="card"><h3>PAES: narrativa y análisis</h3><p>Una ruta para practicar conflicto, narrador, simbolismo y contexto: <em>Frankenstein</em>, <em>Drácula</em>, <em>Niebla</em> y <em>Lazarillo</em>.</p><a class="button" href="${link('guias')}">Abrir guías PAES →</a></article><aside class="card"><h3>Ideas para conversar</h3><p>Lecturas breves para pensar estrategia, identidad y vida cotidiana: <em>El arte de la guerra</em>, <em>Meditaciones</em> y poesía modernista.</p><a class="button" href="${link('libro','&libro=meditaciones')}">Explorar ideas →</a></aside></section></div></main>`}
function how(){return `<main class="page"><div class="wrap"><span class="eyebrow">Así funcionaría el producto</span><h1 style="font-size:clamp(3rem,6vw,5.2rem);max-width:760px">Gratis para entrar. Útil para volver.</h1><section class="study"><article class="card"><h3>Plan gratuito</h3><p>Catálogo inicial, fichas de lectura y una guía de muestra por semana.</p><h3>Plan Umbral</h3><p>Guías completas, simulacros PAES, marcadores, listas de lectura y nuevos packs mensuales.</p></article><aside class="card"><h3>La idea de negocio</h3><p>El texto de dominio público atrae. Las guías propias, la experiencia y la comunidad son lo que puedes convertir en membresía o packs.</p><a class="button" href="${link('unete')}">Ver lista de espera →</a></aside></section></div></main>`}
function render(){let b=books.find(x=>x.id===selected)||books[0];let page=view==='catalogo'?catalogue():view==='libro'?bookPage(b):view==='leer'?internalReader(b):view==='guias'?guideList():view==='guia'?guidePage(b):view==='planes'?plans():view==='checkout'?checkout():view==='recursos'?resources():view==='rutas'?routes():view==='unete'?join():view==='como-funciona'?how():home();document.querySelector('#app').innerHTML=nav()+page+footer();document.title=view==='inicio'?'Umbral — Biblioteca para leer mejor':'Umbral — '+(b?.title||'Biblioteca');if(view==='leer'&&!sourcePdf(b)){leerLoader(b)}document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');let f=btn.dataset.filter;document.querySelector('#catalogue-books').innerHTML=books.filter(b=>f==='todos'||b.place===f).map(bookCard).join('')}));let form=document.querySelector('#join-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#form-message').textContent='¡Listo! Revisa tu correo para confirmar tu suscripción a Umbral.'})}render();

function leerLoader(b){let wrap=document.getElementById('premium-reader');if(wrap&&wrap.classList.contains('premium-pdf')){return;}const art=document.getElementById('reader-text');if(!art){return;}const ctrl=document.getElementById('read-ctrl'),prevBtn=document.getElementById('read-prev'),nextBtn=document.getElementById('read-next'),metaEl=document.getElementById('read-meta'),fill=document.getElementById('read-fill');let pages=[],idx=0,fr=100;function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}function isHead(t){if(t.length>90){return false;}if(/^(cap[ií]tulo|cap[\.\s]|parte|pr[oó]logo|ep[ií]logo|dedicatoria|libro|secci[óo]n|conclusi[óo]n)\b/i.test(t)){return true;}const u=t.replace(/[.,;:!?¡¿"'()\-—]/g,'').trim();return u.length>3&&/^[A-ZÁÉÍÓÚÑÜÇ]+(\s+[A-ZÁÉÍÓÚÑÜÇ]+)*$/.test(u);}function render(i){idx=Math.max(0,Math.min(pages.length-1,i));const seg=pages[idx];let h='';if(idx===0){h+='<div class="p-cover"><h2 class="p-chapter">'+esc(b.title)+'</h2><p class="p-author">'+esc(b.author)+' · '+esc(String(b.year))+'</p></div>';}for(const q of seg){const t=q.trim();h+=isHead(t)?('<h3 class="p-h">'+esc(t)+'</h3>'):('<p>'+esc(t)+'</p>');}art.innerHTML=h;metaEl.textContent=(idx+1)+' / '+pages.length;fill.style.width=pages.length>1?Math.round(((idx+1)/pages.length)*100)+'%':'100%';prevBtn.disabled=idx===0;nextBtn.disabled=idx===pages.length-1;art.scrollTop=0;}fetch('textos/'+encodeURIComponent(b.id)+'.txt').then(r=>{if(!r.ok){throw new Error(String(r.status));}return r.text();}).then(t=>{const raw=t.replace(/\r\n/g,'\n').split(/\n{2,}/).map(x=>x.trim()).filter(x=>x.length);pages=[];let cur=[],sum=0,CHARS=3200;for(const p of raw){sum+=p.length;if(cur.length&&sum>CHARS){pages.push(cur);cur=[];sum=p.length;}cur.push(p);}if(cur.length){pages.push(cur);}if(pages.length){art.classList.remove('kr');ctrl.hidden=false;render(0);}else{art.innerHTML='<p class="reader-loading">No se encontró el texto completo de este título.</p>';}}).catch(()=>{art.innerHTML='<p class="reader-loading">El texto aún no está disponible en esta edición.</p>';});prevBtn.addEventListener('click',()=>{render(idx-1);});nextBtn.addEventListener('click',()=>{render(idx+1);});document.addEventListener('keydown',function kd(e){if(e.key==='ArrowRight'){render(idx+1);e.preventDefault();}else if(e.key==='ArrowLeft'){render(idx-1);e.preventDefault();}});function applyFr(){art.style.fontSize=fr+'%';const sz=document.getElementById('rtool-size');if(sz){sz.textContent=fr+'%';}}document.getElementById('fr-minus').addEventListener('click',()=>{fr=Math.max(70,fr-10);applyFr();});document.getElementById('fr-plus').addEventListener('click',()=>{fr=Math.min(150,fr+10);applyFr();});const themeBtn=document.getElementById('fr-theme');themeBtn.addEventListener('click',()=>{const c=document.getElementById('reader-card');if(c){c.classList.toggle('dark');}});}
